import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.Arrays;

public class UserCreation extends JDialog {
    private JPanel contentPane;

    private JTextField usernameInput;
    private JPasswordField passwordInput;
    private JPasswordField passwordInputCheck;
    private JButton OKButton;
    private JLabel detailsText;
    private JLabel userLabel;
    private JLabel pass1Label;
    private JLabel pass2Label;

    public UserCreation() {
        setContentPane(contentPane);
        setModal(true);
        getRootPane().setDefaultButton(OKButton);
        this.setResizable(false);
        this.setBounds(200, 200, 400, 200);


        OKButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                onOK();
            }
        });

        contentPane.registerKeyboardAction(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                onCancel();
            }
        }, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                onCancel();
            }
        });

    }

    private void onCancel() {
        // add your code here if necessary
        dispose();
    }


    public static void main(String[] args) {
        UserCreation dialog = new UserCreation();
        dialog.pack();
        dialog.setVisible(true);
        System.exit(0);
    }

    private void onOK() {
        // add your code here if necessary
        //DatabaseHandler databaseHandler = new DatabaseHandler();
        String userName = usernameInput.getText();

        if (userInputFormatCheck(userName.toCharArray())) {
            if (DatabaseHandler.getUserFromDatabase(userName) == null) {
                userLabel.setForeground(Color.BLACK);
                detailsText.setText("Enter Username and Password");


                if (Arrays.equals(passwordInput.getPassword(), passwordInputCheck.getPassword())) {
                    if (userInputFormatCheck(passwordInput.getPassword())) {


                        String salt = Password.genSalt(256).get();
                        String key = Password.hashPassword(passwordInput.getPassword(), salt).get();
                        pass1Label.setForeground(Color.BLACK);
                        pass2Label.setForeground(Color.BLACK);
                        DatabaseHandler.writeToUserDatabase(userName, key, salt);
                        dispose();
                    } else {
                        pass1Label.setForeground(Color.RED);
                        pass2Label.setForeground(Color.RED);
                        detailsText.setText("Please use only alphanumeric characters");
                        passwordInput.setText("");
                        passwordInputCheck.setText("");
                    }


                } else {
                    pass1Label.setForeground(Color.RED);
                    pass2Label.setForeground(Color.RED);
                    detailsText.setText("Passwords do not match");
                    passwordInputCheck.setText("");
                }

            } else {
                detailsText.setText("User exists");
                userLabel.setForeground(Color.RED);
            }
        } else {
            detailsText.setText("Please use only alphanumeric characters");
            userLabel.setForeground(Color.RED);
        }

    }

    private boolean userInputFormatCheck(char[] userInput) {
        if (userInput.length < 1) {
            return false;
        }

        for (char c : userInput) {

            if (!Character.isLetterOrDigit(c)) {
                return false;
            }
        }
        return true;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(5, 4, new Insets(0, 0, 0, 0), -1, -1));
        passwordInputCheck = new JPasswordField();
        contentPane.add(passwordInputCheck, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        OKButton = new JButton();
        OKButton.setText("OK");
        contentPane.add(OKButton, new com.intellij.uiDesigner.core.GridConstraints(4, 1, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        passwordInput = new JPasswordField();
        passwordInput.setText("");
        contentPane.add(passwordInput, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        detailsText = new JLabel();
        detailsText.setText("Enter Username and Password");
        contentPane.add(detailsText, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        usernameInput = new JTextField();
        usernameInput.setText("");
        contentPane.add(usernameInput, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        userLabel = new JLabel();
        userLabel.setText("Username");
        contentPane.add(userLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        pass1Label = new JLabel();
        pass1Label.setText("Password");
        contentPane.add(pass1Label, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        pass2Label = new JLabel();
        pass2Label.setText("Password Again");
        contentPane.add(pass2Label, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}